library(Rcpp)
    
 Rcpp.package.skeleton("Eagle", cpp_files=c(
            "magma_qr.cpp"  ,
            "ReshapeM_rcpp.cpp"  ,
            "RcppExampleEigen_m_v2.cpp"  ,
            "getRowColumn.cpp"  ,
            "CreateASCIInospace_PLINK.cpp"  ,
            "CreateASCIInospace.cpp"  ,
            "ReadBlock.cpp"  ,
            "createMt_ASCII_rcpp.cpp"  ,
            "ReshapeM_rcpp.cpp"  ,
            "calculate_reduced_a_rcpp.cpp"  ,
            "removeRow.cpp"  ,
            "removeColumn.cpp"  ,
 "fasttimer.cpp"  ,
            "calculate_a_and_vara_rcpp.cpp"  ,
            "calculate_a_and_vara_batch_rcpp.cpp"  ,
            "createM_ASCII_rcpp.cpp"  ,
            "extract_geno_rcpp.cpp"  ,
            "calculateMMt_rcpp.cpp"  ,
            "getNumColumns.cpp"  ,
            "getNumRows.cpp"  
             ),    
    example_code=FALSE, code_files=c(
            "onAttach.R", 
            "FPR4AM.R",
            "ReadMarker.R",
            "ReadMap.R",
            "ReadZmat.R",
            "ReadPheno.R",
            "AM.R", 
            "OpenGUI.R", 
            "GenomicRel.R", 
            "doquiet.R", 
            "ReshapeM.R", 
            "form_results.R", 
            "print_title.R", 
            "build_design_matrix.R", 
            "calcMMt.R", 
            "calc_extBIC.R", 
            "calcVC.R", 
            "print_header.R", 
            "print_final.R", 
            "print_results.R", 
            "find_qtl.R", 
            "fullpath.R", 
            "emma_delta_ML_dLL_w_Z.R", 
            "emma_eigen_L_w_Z.R", 
            "emma_eigen_R_w_Z.R", 
            "emma_delta_REML_dLL_w_Z.R", 
            "emma_delta_REML_LL_w_Z.R", 
            "emma_MLE.R", 
            "emma_REMLE.R", 
            "emma_delta_ML_LL_wo_Z.R", 
            "emma_eigen_L_wo_Z.R", 
            "emma_eigen_R_wo_Z.R", 
            "emma_delta_ML_LL_w_Z.R", 
            "emma_misc.R", 
            "check_for_NA_in_trait.R", 
            "check_inputs_mlam.R", 
            "calculateMMt.R", 
            "calculateMMt_sqrt_and_sqrtinv.R", 
            "calculateH.R", 
            "calculateP.R", 
            "calculate_reduced_a_batch.R", 
            "calculate_reduced_a.R", 
            "calculate_a_and_vara.R", 
            "calculate_a_and_vara_batch.R", 
            "calculate_reduced_vara.R", 
            "check_inputs.R", 
            "create_ascii.R", 
            "extract_geno.R", 
            "constructX.R", 
            "summary_am.R"   ) ) 
  ## running roxygen2  
 library(roxygen2) 
 setwd("./Eagle")  
  roxygenise() 
  
