# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ReadBlock <- function(tmpfname, start_row, numcols, numrows_in_block) {
    .Call('_Lion_ReadBlock', tmpfname, start_row, numcols, numrows_in_block)
}

ReadBlockBin <- function(binfname, start_row, numcols, numrows_in_block) {
    .Call('_Lion_ReadBlockBin', binfname, start_row, numcols, numrows_in_block)
}

ReshapeM_rcpp <- function(fnameM, fnameMt, indxNA, dims) {
    .Call('_Lion_ReshapeM_rcpp', fnameM, fnameMt, indxNA, dims)
}

calculateMMt_rcpp <- function(f_name, max_memory_in_Gbytes, num_cores, selected_loci, dims, quiet, message) {
    .Call('_Lion_calculateMMt_rcpp', f_name, max_memory_in_Gbytes, num_cores, selected_loci, dims, quiet, message)
}

calculate_a_and_vara_batch_rcpp <- function(numreps, f_name, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a, quiet, message) {
    .Call('_Lion_calculate_a_and_vara_batch_rcpp', numreps, f_name, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a, quiet, message)
}

calculate_a_and_vara_rcpp <- function(f_name, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a, quiet, message) {
    .Call('_Lion_calculate_a_and_vara_rcpp', f_name, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a, quiet, message)
}

calculate_reduced_a_rcpp <- function(f_name, varG, P, y, max_memory_in_Gbytes, dims, selected_loci, quiet, message) {
    .Call('_Lion_calculate_reduced_a_rcpp', f_name, varG, P, y, max_memory_in_Gbytes, dims, selected_loci, quiet, message)
}

createM_ASCII_rcpp <- function(f_name, f_name_tmp, type, AA, AB, BB, max_memory_in_Gbytes, dims, quiet, message, missing) {
    .Call('_Lion_createM_ASCII_rcpp', f_name, f_name_tmp, type, AA, AB, BB, max_memory_in_Gbytes, dims, quiet, message, missing)
}

createM_BIN_rcpp <- function(f_name, f_name_bin, type, AA, AB, BB, max_memory_in_Gbytes, dims, quiet, message, missing) {
    .Call('_Lion_createM_BIN_rcpp', f_name, f_name_bin, type, AA, AB, BB, max_memory_in_Gbytes, dims, quiet, message, missing)
}

createMt_ASCII_rcpp <- function(f_name, f_name_tmp, type, max_memory_in_Gbytes, dims, quiet, message) {
    invisible(.Call('_Lion_createMt_ASCII_rcpp', f_name, f_name_tmp, type, max_memory_in_Gbytes, dims, quiet, message))
}

createMt_BIN_rcpp <- function(f_name_in, f_name_out, type, max_memory_in_Gbytes, dims, quiet, message) {
    invisible(.Call('_Lion_createMt_BIN_rcpp', f_name_in, f_name_out, type, max_memory_in_Gbytes, dims, quiet, message))
}

create_vcf_BIN_rcpp <- function(f_name, f_name_bin_M, f_name_bin_Mt, max_memory_in_Gbytes, quiet, message) {
    .Call('_Lion_create_vcf_BIN_rcpp', f_name, f_name_bin_M, f_name_bin_Mt, max_memory_in_Gbytes, quiet, message)
}

extract_geno_Mt_rcpp <- function(f_name, selected_locus, dims) {
    .Call('_Lion_extract_geno_Mt_rcpp', f_name, selected_locus, dims)
}

extract_geno_rcpp <- function(f_name, max_memory_in_Gbytes, selected_locus, dims) {
    .Call('_Lion_extract_geno_rcpp', f_name, max_memory_in_Gbytes, selected_locus, dims)
}

fasttimer <- function() {
    .Call('_Lion_fasttimer')
}

getRowColumn <- function(fname) {
    .Call('_Lion_getRowColumn', fname)
}

magma_qr <- function(X, numgpus, printInfo, fname, message) {
    .Call('_Lion_magma_qr', X, numgpus, printInfo, fname, message)
}

