shiny:
  proxy:
    title: CSIRO Eagle Demo
    logo-url: http://140.253.154.240/csiro_logo/CSIRO_Grad_RGB_lr.jpg
    landing-page: /
    heartbeat-rate: 5000
    heartbeat-timeout: 20000
    container-wait-time: 60000
    port: 8080
    admin-groups: scientists    
    # Example: 'simple' authentication configuration
    # authentication: simple
    authentication: none
    users:
    - name: josh
      password: password
      groups: scientists
    # Docker configuration
    # https://docs.docker.com/engine/security/certificates/#understanding-the-configuration
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      port-range-start: 20200
    support:
      container-log-path: ./container-logs
      mail-to-address: josh.bowden@csiro.au
  apps:
  - name: Eagle
    docker-cmd: ["R", "-e shiny::runApp('/R/library/Eagle/shiny_app',port=3838,host='0.0.0.0')"]
    docker-image: imtsc-cont-reg.it.csiro.au/eagle/mro_eagle_cran:latest
    docker-memory: 1g
    docker-user: docker
  - name: imtsc-cont-reg.it.csiro.au_eagle
    docker-cmd: ["R", "-e shiny::runApp('/R/library/Eagle/shiny_app')"]
    docker-image: imtsc-cont-reg.it.csiro.au/eagle/mro_eagle_acc2:latest
    docker-memory: 1g
    docker-user: docker

logging:
  level:
      org.springframework.web.util: DEBUG
      c.s.docker.client.DefaultDockerClient: DEBUG
  file:
      shinyproxy.log
