# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ReadBlock <- function(asciifname, start_row, numcols, numrows_in_block) {
    .Call('_EagleGPU_ReadBlock', asciifname, start_row, numcols, numrows_in_block)
}

ReshapeM_rcpp <- function(fnameM, fnameMt, indxNA, dims) {
    .Call('_EagleGPU_ReshapeM_rcpp', fnameM, fnameMt, indxNA, dims)
}

calculateMMt_rcpp <- function(f_name_ascii, max_memory_in_Gbytes, num_cores, selected_loci, dims, quiet, message) {
    .Call('_EagleGPU_calculateMMt_rcpp', f_name_ascii, max_memory_in_Gbytes, num_cores, selected_loci, dims, quiet, message)
}

calculate_a_and_vara_batch_rcpp <- function(numreps, f_name_ascii, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a, quiet, message) {
    .Call('_EagleGPU_calculate_a_and_vara_batch_rcpp', numreps, f_name_ascii, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a, quiet, message)
}

calculate_a_and_vara_rcpp <- function(f_name_ascii, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a, quiet, message) {
    .Call('_EagleGPU_calculate_a_and_vara_rcpp', f_name_ascii, selected_loci, inv_MMt_sqrt, dim_reduced_vara, max_memory_in_Gbytes, dims, a, quiet, message)
}

calculate_reduced_a_rcpp <- function(f_name_ascii, varG, P, y, max_memory_in_Gbytes, dims, selected_loci, quiet, message) {
    .Call('_EagleGPU_calculate_reduced_a_rcpp', f_name_ascii, varG, P, y, max_memory_in_Gbytes, dims, selected_loci, quiet, message)
}

createM_ASCII_rcpp <- function(f_name, f_name_ascii, type, AA, AB, BB, max_memory_in_Gbytes, dims, quiet, message, missing) {
    .Call('_EagleGPU_createM_ASCII_rcpp', f_name, f_name_ascii, type, AA, AB, BB, max_memory_in_Gbytes, dims, quiet, message, missing)
}

createMt_ASCII_rcpp <- function(f_name, f_name_ascii, type, max_memory_in_Gbytes, dims, quiet, message) {
    invisible(.Call('_EagleGPU_createMt_ASCII_rcpp', f_name, f_name_ascii, type, max_memory_in_Gbytes, dims, quiet, message))
}

extract_geno_rcpp <- function(f_name_ascii, max_memory_in_Gbytes, selected_locus, dims) {
    .Call('_EagleGPU_extract_geno_rcpp', f_name_ascii, max_memory_in_Gbytes, selected_locus, dims)
}

fasttimer <- function() {
    .Call('_EagleGPU_fasttimer')
}

getRowColumn <- function(fname) {
    .Call('_EagleGPU_getRowColumn', fname)
}

magma_qr <- function(X, numgpus, printInfo, fname, message) {
    .Call('_EagleGPU_magma_qr', X, numgpus, printInfo, fname, message)
}

